### ISSUE TITLE
Propuesta de mejora en la sección de Pandas

### ISSUE THREAD

**Issue by jlopezper** [koldLight/curso-python-analisis-datos#1]
En la sección **Selección por condiciones** del notebook relativo a Pandas se menciona:

> **Nota:** mira cómo en el código anterior hemos seleccionado la columna `distrito` usando la sintaxis sumamente compacta `alquiler.distrito`. 

Yo aclararía que, aunque es válido, es más conveniente utilizar la notación de corchetes puesto que con la de puntuación se podrían sobrescribir métodos de la clase `pandas.DataFrame`.

Gracias por publicar este recurso.

**Comment by koldLight** [comment]
Hola, gracias por el comentario.

Lleva a una discusión interesante: ¿corchetes o punto? Que creo se puede resumir en estos pros de cada una de ellas:
* Corchetes: funciona siempre (aunque la columna tenga espacios, sea palabra reservada, en la creación de columnas, etc), no sobrescribes sin querer y quizás es _más pythonista_ (acceder igual que con los dicts).
* Punto: más compacto, más cómodo de escribir, más legible (sobre todo al concatenar con funciones) y el autocompletado de los IDEs suele funcionar mejor.

Y también a un dilema. De la gente que sigue el curso, hay perfiles muy diferentes: los ya programadores, que sí agradecen comentarios extra sobre estilo, posibles problemas, etc. y los principiantes, que se sienten abrumados con toda la nueva información y un debate como este les confundirá más.

Creo que lo voy a resolver añadiendo pequeñas secciones marcadas para usuarios avanzados. Algo así como _nota avanzada_ o _para profundizar_. Y en este caso, añadiendo un link para que cada uno decida cuál prefiere (p.e. este de [dataschool](https://www.dataschool.io/pandas-dot-notation-vs-brackets/))
